apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.host }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
    sector: {{ .Values.statefulset.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.statefulset.port }}
      targetPort: {{ .Values.statefulset.port }}
