apiVersion: v1
kind: Service
metadata:
  name: odoo-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
    sector: {{ .Values.deployment.name }}
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8069
      targetPort: 8069
      nodePort: 30000
