apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc-claim
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: db-local-sc
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvc-claim
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: odoo-local-sc
  resources:
    requests:
      storage: 1Gi